spring.application.name=${SPRING_APPLICATION_NAME}

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hibernate
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

# JWT configuration
truyen247.app.jwtSecret=${TRUYEN247_APP_JWT_SECRET}
truyen247.app.jwtExpirationMs=${TRUYEN247_APP_JWT_EXPIRATION_MS}

# AWS S3 configuration
cloud.aws.credentials.accessKey=${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
cloud.aws.credentials.secretKey=${CLOUD_AWS_CREDENTIALS_SECRETKEY}
cloud.aws.region.static=${CLOUD_AWS_REGION_STATIC}
cloud.aws.s3.bucket-name=${CLOUD_AWS_S3_BUCKET_NAME}
