spring.application.name=${SPRING_APPLICATION_NAME}

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hibernate
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

# JWT configuration
truyen247.app.jwtSecret=${TRUYEN247_APP_JWT_SECRET}
truyen247.app.jwtExpirationMs=${TRUYEN247_APP_JWT_EXPIRATION_MS}

# AWS S3 configuration
cloud.aws.credentials.accessKey=${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
cloud.aws.credentials.secretKey=${CLOUD_AWS_CREDENTIALS_SECRETKEY}
cloud.aws.region.static=${CLOUD_AWS_REGION_STATIC}
cloud.aws.s3.bucket-name=${CLOUD_AWS_S3_BUCKET_NAME}

# File upload configuration
spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}

# OAuth2 Google configuration
oauth2.client.registration.google.client-id=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
oauth2.client.registration.google.client-secret=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
oauth2.client.registration.google.redirect-uri=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI}
oauth2.client.registration.google.scope=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE}

# SEPay API configuration
sepay.api.url=${SEPAY_API_URL}
sepay.api.token=${SEPAY_API_TOKEN}
sepay.account.number=${SEPAY_ACCOUNT_NUMBER}
payment.scheduler.limit=${PAYMENT_SCHEDULER_LIMIT}
payment.scheduler.validAccountNumbers=${PAYMENT_SCHEDULER_VALID_ACCOUNT_NUMBERS}
payment.scheduler.paymentPrefix=${PAYMENT_SCHEDULER_PAYMENT_PREFIX}


